apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-server
  namespace: spire
data:
  server.conf: |-
    server {
      bind_address = "0.0.0.0"
      bind_port = "8081"
      socket_path = "/tmp/spire-server/private/api.sock"
      trust_domain = "coastal-containers.example"
      data_dir = "/run/spire/data"
      log_level = "DEBUG"
      ca_key_type = "rsa-2048"

      ca_subject = {
        country = ["UK"],
        organization = ["CoastalContainers"],
        common_name = "Coastal Containers Ltd",
      }
    }

    plugins {
      DataStore "sql" {
        plugin_data {
          database_type = "sqlite3"
          connection_string = "/run/spire/data/datastore.sqlite3"
        }
      }

      NodeAttestor "k8s_psat" {
        plugin_data {
          clusters = {
            # NOTE: Change this to your cluster name
            "kind-cargo-clipper" = {
              service_account_allow_list = ["spire:spire-agent"]
            }
          }
        }
      }

      KeyManager "memory" {
        plugin_data {}
      }

      Notifier "k8sbundle" {
        plugin_data {
        # When left unset, this plugin automatically publishes bundle contents from the in-cluster SPIRE server to the bundle.crt key within the spire-bundle ConfigMap
        }
      }
      UpstreamAuthority "spire" {
        plugin_data = {
          server_address      = "coastal-containers-control-plane"
          server_port         = 8081
          workload_api_socket = "/run/spire/sockets/root-agent.sock"
        }
      }
    }

    health_checks {
      listener_enabled = true
      bind_address = "0.0.0.0"
      bind_port = "8080"
      live_path = "/live"
      ready_path = "/ready"
    }
