apiVersion: v1
kind: ServiceAccount
metadata:
  name: server
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - port: 443
      targetPort: 8443
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccountName: server
      containers:
        - name: server
          image: manifest-server:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /spire-agent-socket
              readOnly: true
            - name: svids
              mountPath: /var/run/secrets/svids
            - name: spiffe-helper-config
              mountPath: /opt/spire/config
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///spire-agent-socket/agent.sock
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: spire-agent-socket
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
        - name: svids
          emptyDir: {}
        - name: spiffe-helper-config
          configMap:
            name: server-helper-config
