# app.yaml
kind: Pod
apiVersion: v1
metadata:
  name: pilot-boat-0
  labels:
    app: pilot-boat-0
spec:
  initContainers:
    - name: proxy-init
      image: openpolicyagent/proxy_init:v8
      args: ["-p", "8081", "-o", "8081", "-u", "1111", "-w", "8282"]
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
        runAsNonRoot: false
        runAsUser: 0
  containers:
    - name: envoy
      image: envoyproxy/envoy:v1.27.0
      imagePullPolicy: Always
      args:
        - "envoy"
        - "--config-path"
        - "/config/envoy.yaml"
      ports:
        - containerPort: 9002
      volumeMounts:
        - name: proxy-config
          mountPath: /config
          readOnly: true
        - name: spire-agent-socket
          mountPath: /spire-agent-socket
          readOnly: true
      env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///spire-agent-socket/agent.sock
        - name: ENVOY_UID
          value: "1111"
    - name: curl
      image: alpine/curl
      command: ["sleep", "infinity"]
  volumes:
    - name: proxy-config
      configMap:
        name: pilot-boat-0-envoy
    - name: spire-agent-socket
      csi:
        driver: "csi.spiffe.io"
        readOnly: true
