apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-app
          image: backend-app:v1
          ports:
            - containerPort: 8443
          volumeMounts:
            - mountPath: "/certs/frontend-cert-chain.pem"
              subPath: "ca.crt"
              name: backend
              readOnly: true
            - mountPath: "/certs/backend.pem"
              subPath: "tls.crt"
              name: backend
              readOnly: true
            - mountPath: "/certs/backend-key.pem"
              subPath: "tls.key"
              name: backend
              readOnly: true
      volumes:
        - name: backend
          secret:
            secretName: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: cm
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
