apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-app
          image: frontend-app:v1
          ports:
            - containerPort: 8443
          volumeMounts:
            - mountPath: "/certs/backend-cert-chain.pem"
              subPath: "ca.crt"
              name: frontend
              readOnly: true
            - mountPath: "/certs/frontend.pem"
              subPath: "tls.crt"
              name: frontend
              readOnly: true
            - mountPath: "/certs/frontend-key.pem"
              subPath: "tls.key"
              name: frontend
              readOnly: true
      volumes:
        - name: frontend
          secret:
            secretName: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cm
  annotations:
    projectcontour.io/upstream-protocol.tls: "443"
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
