apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-alpha
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-alpha
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fleet-alpha
  template:
    metadata:
      labels:
        app: fleet-alpha
    spec:
      serviceAccountName: fleet-alpha
      containers:
        - name: fleet-alpha
          image: workload:latest
          imagePullPolicy: Never
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///spiffe-workload-api/spire-agent.sock
          volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
      volumes:
        - name: spiffe-workload-api
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
