apiVersion: v1
kind: Namespace
metadata:
  name: pirate-coast
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pirate-ship
  namespace: pirate-coast
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pirate-ship
  namespace: pirate-coast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pirate-ship
  template:
    metadata:
      labels:
        app: pirate-ship
    spec:
      serviceAccountName: pirate-ship
      containers:
        - name: pirate-ship
          image: nginx:1.25
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///spiffe-workload-api/spire-agent.sock
          volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true
      volumes:
        - name: spiffe-workload-api
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
---
kind: Service
apiVersion: v1
metadata:
  name: pirate-ship
  namespace: pirate-coast
  labels:
    name: pirate-ship
spec:
  selector:
    name: pirate-ship
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort
