apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  type: ExternalName
  externalName: coastal-containers-control-plane
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      serviceAccountName: client
      initContainers:
        - name: agent
          image: spiffe/spire-agent:latest
          imagePullPolicy: Never
          command: ["/opt/spire/bin/spire-agent", "api", "fetch", "x509", "-write", "/tmp/svids", "-socketPath", "/spire-agent-socket/agent.sock"]
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /spire-agent-socket
              readOnly: true
            - name: svids
              mountPath: /tmp/svids
      containers:
        - name: client
          image: client:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: svids
              mountPath: /var/run/secrets/svids
          env:
            - name: PORT
              value: "9443"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: spire-agent-socket
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
        - name: svids
          emptyDir: {}
